Client side routing implementation
neo4j-labs/neo4rs pull request #205
Opened 2024-12-16 10:51 UTC by madchicken

This PR is a draft implementation of the client-side routing for new4j clusters.
The PR implements the ROUTE message for both the stable bolt implementation and the unstable one. Tests are being performed on the stable version of the protocol since the new one is still giving me problems in deserialization.
What the PR is still missing:

- [ ] Testing: I am currently testing the driver on a real cluster but I have no guarantee of the performance and stability of the routing algorithm 
- [ ] Bookmarks are not supported at the moment (the array is always sent empty)
- [ ] The maximum supported version of the protocol is now 4.3 but we miss some of the features the protocol should expose from this version (the `patch_bolt` field for example)
- [ ] Only the round-robin algorithm is currently implemented as a routing strategy. Maybe we want to implement a LeastUsed algo and make it configurable.
- [ ] There is no handling of the initial routing context: it is always empty.

Additional Notes:
- The lock mechanism for refreshing the routing table is sub-optimal (to use an euphemism). We should try to be smarter and use a different method to check for a new routing table.
- Extra fields in the route message are not implemented yet (part of v4.4)

2024-12-18 17:07 UTC, knutwalker commented
Hey, thanks for this PR, this helps a lot!

I went over the changes and don't have anything to add, but I also did look in detail at the actual routing protocol and algorithms.

I'm ok with merging something before dealing with all limitations. In particular, I think it's fine to not support the routing context, bookmarks, only have partial 4.3 support, only having one routing strategy at the beginning. We don't need to have everything figured out upfront and can do this in steps/multiple PRs.
I would also be ok with only adding it to the new protocol implementation.

I've been thinking about the testing a bit (or a lot) lately; I don't like the amount of integration tests compared to what the unit tests do. Especially when testing bolt protocol details of a non-happy path, it can be either impossible or very difficult to setup.
The current setup is fine to actually run something against a one-and-done database, but it doesn't scale as well as I would like it to be.

I have half an idea to rewrite the core parts with the connection IO and pooling being abstracted out. I would like to be able to do more simulation testing where exact IO operations can be simulated in the tests without having to have an actual db to setup. I'd also like to move async out from the core to some outer layer. Maybe this goes in the sans-io direction, maybe it'll look a bit different.

2024-12-19 15:28 UTC, knutwalker commented
> I will remove the implementation of the client-side routing for the stable protocol and leave it only when the `unstable-bolt-protocol-impl-v2` feature is active.

great!


> One thing I need to understand is this: when selecting the server in the routing table, should I use the `bolt` protocol or stick with `neo4j` for the final connection? I think this is very important for the server, isn't it?

There shouldn't be a need for any scheme. The first connection uses the scheme to determine the initial routing and the encryption to use. When connecting to a server from the routing table, you use the same encryption settings (and, when supported, routing context) and directly connect to that socket address, without going through the bolt/neo4j scheme parsing again. That is what the product drivers do, at least. That looks like this requires some changes to the pool creation, essentially using the same ConnectionInfo, but with only the host/port replaced.

2024-12-19 15:41 UTC, madchicken commented
> There shouldn't be a need for any scheme. The first connection uses the scheme to determine the initial routing and the encryption to use. When connecting to a server from the routing table, you use the same encryption settings (and, when supported, routing context) and directly connect to that socket address, without going through the bolt/neo4j scheme parsing again. That is what the product drivers do, at least. That looks like this requires some changes to the pool creation, essentially using the same ConnectionInfo, but with only the host/port replaced.

Yes, sorry...I realized that too.

2024-12-19 18:36 UTC, madchicken commented
@knutwalker please take a look at my last commit where I had to modify the main Graph interface. I had essentially to expose the `Operation::Read/Write` parameter only for the new protocol implementation. I hope it makes sense.
I also added a note in the description of the PR about the retry mechanism.

2025-01-05 17:23 UTC, madchicken commented
@knutwalker I have finished my work on this first implementation of the client-side routing. I tested it in a simple local cluster and I am now running it on a k8s cluster and it seems to work properly. I still don't have any data about the performance impact regarding the locking mechanism implemented on the routing table the driver holds after the initialization.

2025-01-07 09:10 UTC, knutwalker commented
4.4 IT failure could be related to #209

2025-01-08 20:03 UTC, knutwalker requested changes
This is very good, thanks for adding all this. I do have few comments I'd like to be resolved before merging in, but it isn't anything bigger (I hope) and some are more ideas and thoughts than suggestions.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/bolt/request/route.rs
> +#[cfg(feature = "unstable-bolt-protocol-impl-v2")]
The whole `crate::bolt` module is already behind the feature flag, we don't need to repeat it within this mod.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/bolt/request/route.rs
> +                    map.serialize_entry(k.to_string().as_str(), v.to_string().as_str())?;
Could access `.value` directly and avoid an intermediate string copy.

```suggestion
                    map.serialize_entry(k.value.as_str(), v.value.as_str())?;
```

2025-01-08 20:03 UTC, knutwalker commented on lib/src/bolt/request/route.rs
> +        }
If I follow this correctly, having no `extra` and no `db` will result in a third `null` field, which is either `db` or `extra`, based on the protocol version.

That should be fine, though I would like to make the difference between the protocol versions a bit more explicit, that is, not to have separate `db` and `extra` fields, but an enum:

```rust
enum RouteExtra {
    V43 { db: Option<String> },   // or just tuple variants
    V44 { extra: Option<Extra> }, // would also be fine
}

struct Route {
  // ...
  extra: RouteExtra
}
```

2025-01-08 20:03 UTC, knutwalker commented on lib/src/bolt/request/route.rs
> +    fn serialize() {
A 4.4 version of the "with db" test and/or imp_user would also be great.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/config.rs
> +        self.0.serialize(serializer)
serde as an `rc` feature, which allows it to serialize `Rc` and `Arc`. Just to make this more explicit that we don't require that feature or that the serialize changes when that feature is active, I would explicitly deref the Arc:

```suggestion
        (*self.0).serialize(serializer)
// or   (**self).serialize(serializer)
```

2025-01-08 20:03 UTC, knutwalker commented on lib/src/config.rs
> +
I would like to not have a default impl for this type, since the default value depends on whatever is configured on the server (I removed it in #197 for that reason). It also doesn't seem to be used anywhere and having a Default impl would invite things like `unwrap_or_default` instead of leaving the db value empty or null to let the server use the correct default database.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/connection.rs
> +                "Client-side routing is in experimental mode.",
👍

2025-01-08 20:03 UTC, knutwalker commented on lib/src/graph.rs
> +    Normal(ConnectionPool),
Maybe `Unrouted` instead of `Normal`? Normal sounds like routed is some exceptional state, but it should also be normal for the driver to do client side routing.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/graph.rs
> +    pub async fn run_read(&self, q: Query) -> Result<()> {
I'm not against this, just wondering if there is a use-case for a read-only run. Usually run is meant for write queries that you want to run in a fire-and-forget style. Reading things but also discarding the result doesn't seem to work together very well 😅

2025-01-08 20:03 UTC, knutwalker commented on lib/src/messages.rs
> +        debug!("run query: {} with extra params {:?}", query, extra);
I'm a bit on the edge about this debug log, since it might write sensitive information in the query into some log that could be visible to unintended eyes. The server works around that by auto-parameterizing every literal and also not logging the parameters, but we don't know in the client if the user is already sending their values as params or have them inlined in the query and it's not typical for a Neo4j driver to parse the query in any form. It's quite an edge-case, but I'd feel a bit at ease without logging the query by default. We could add an opt-in cargo feature that enables this log, or maybe only log the first few characters, or until the first whitespace.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/pool.rs
> +        trace!("creating new connection");
Good call 👍

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/connection_registry.rs
> +            debug!("Routing table is not expired");
This else arm is for the `try_lock`, a more appropriate log message would be "Another connection is already checking if the routing table needs updating" (or move the else into the mutex guard region).

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/connection_registry.rs
> +            if self.connections.is_empty() || now - *guard > self.ttl.load(Ordering::Relaxed) {
`SystemTime` can go backwards if the system clock is adjusted. It doesn't look like we actually need the timestamp itself, only a check if more than `ttl` seconds have passed. I would suggest changing `creation_time` to an `Arc<Mutex<Instant>>`.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/connection_registry.rs
> +                };
We shouldn't really have to do this, and also not setup tls again, though that would require a refactor of the whole connection pool. I think we can leave this as a task for the future.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/load_balancing/round_robin_strategy.rs
> +            .ok();
`ok` turns the result into an option, but doesn't otherwise do anything. If you mean to discard the result, I would do this more explicit with `let _ = ...`.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/mod.rs
> +            Version::V4_4 => Route {
This should be the case for all versions >= 4.4 and Version already implements Ord. This seems like a good spot to forget to update when newer protocol versions are added:

```suggestion
        match version.cmp(&Version::V4_4) {
            std::cmp::Ordering::Equal | std::cmp::Ordering::Greater => Route {
```

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/mod.rs
> +        };
We can save a few string clones here

```suggestion
        let (db, imp_user) = if let Some(extra) = self.extra.as_ref() {
            let db = extra.db.as_deref().unwrap_or("null");
            let imp_user = extra.imp_user.as_deref().unwrap_or("null");
            (db, imp_user)
        } else {
            let db = self.db.as_deref().unwrap_or("null");
            let imp_user = "null";
            (db, imp_user)
        };
```

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/mod.rs
> +                .join(", ")
If we want to save on these allocations as well, there is the `joinery` crate which gives you an iterator version of `join`

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/routed_connection_manager.rs
> +        // while we refresh the routing table. We should probably have a separate thread that refreshes the routing
Another approach could be to spawn a tokio task that sleeps for the ttl or until a few seconds before and refreshes in the background, so that the check during this get is pretty much always up-to-date.

2025-01-08 20:03 UTC, knutwalker commented on lib/src/txn.rs
> +                operation: Operation::Write, // TODO: pass the operation from the outside
couldn't you pass this already, the operation is available in the `impl_start_tx_on` function?

2025-01-08 20:03 UTC, knutwalker commented on lib/tests/use_default_db.rs
>      }
You could save a bit code duplication here:

```suggestion
    #[cfg(feature = "unstable-bolt-protocol-impl-v2")]
    let query_stream = graph
        .execute_on("system", query("SHOW DEFAULT DATABASE"), Operation::Read)
        .await;

    #[cfg(not(feature = "unstable-bolt-protocol-impl-v2"))]
    let query_stream = graph
        .execute_on("system", query("SHOW DEFAULT DATABASE"))
        .await;

    let default_db = query_stream
        .unwrap()
        .column_into_stream::<String>("name")
        .try_fold(None::<String>, |acc, db| async { Ok(acc.or(Some(db))) })
        .await
        .unwrap()
        .unwrap();

    if default_db != dbname {
        eprintln!(
            concat!(
                "Skipping test: The test must run against a testcontainer ",
                "or have `{}` configured as the default database"
            ),
            dbname
        );
        return;
    }
```

2025-01-08 20:03 UTC, knutwalker commented on lib/tests/use_default_db.rs
> +    }
And here as well:

```suggestion
    #[cfg(feature = "unstable-bolt-protocol-impl-v2")]
    let query_stream = graph
        .execute_on(
            dbname.as_str(),
            query("MATCH (n:Node {uuid: $uuid}) RETURN count(n) AS result")
                .param("uuid", id.to_string()),
            Operation::Read,
        )
        .await;

    #[cfg(not(feature = "unstable-bolt-protocol-impl-v2"))]
    let query_stream = graph
        .execute_on(
            dbname.as_str(),
            query("MATCH (n:Node {uuid: $uuid}) RETURN count(n) AS result")
                .param("uuid", id.to_string()),
        )
        .await;

    let count = query_stream
        .unwrap()
        .column_into_stream::<u64>("result")
        .try_fold(0, |sum, count| async move { Ok(sum + count) })
        .await
        .unwrap();

    assert_eq!(count, 1);
```

2025-01-08 20:03 UTC, knutwalker commented on lib/src/routing/connection_registry.rs
> +            debug!("Routing table is not expired");
Also, I guess if a connection can't get the lock, it is likely that another one is updating the routing table (or, less likely, it just happened to be in the small window of it checking). That is, not getting the lock can likely mean that the connection is out-of-date and should not continue. Blocking on the lock would make sure that a connection never uses a stale routing table (With the caveat you mentioned in the TODO further down).

2025-01-09 10:22 UTC, madchicken commented on lib/src/bolt/request/route.rs
> +        }
Oh, I like this!

2025-01-09 11:08 UTC, madchicken commented on lib/src/txn.rs
> +                operation: Operation::Write, // TODO: pass the operation from the outside
damn, you are right. I got confused by the `pub` declaration of the function, but it's at `crate` level...

2025-01-09 11:14 UTC, madchicken commented on lib/src/routing/mod.rs
> +                .join(", ")
Yes, but I didn't want to add another dependency just for the Display implementation I used in the logs. If you think it will also be useful in the future, I can add it.

2025-01-09 11:17 UTC, madchicken commented on lib/src/routing/routed_connection_manager.rs
> +        // while we refresh the routing table. We should probably have a separate thread that refreshes the routing
Correct. This was my other idea, but I wanted an easy solution first and then improve the code. I would implement the thread solution in a new PR if you agree

2025-01-09 11:42 UTC, knutwalker commented on lib/src/routing/mod.rs
> +                .join(", ")
No, it's fine to leave it as is.

2025-01-09 11:43 UTC, knutwalker commented on lib/src/routing/routed_connection_manager.rs
> +        // while we refresh the routing table. We should probably have a separate thread that refreshes the routing
Sure, sounds good!

2025-01-09 16:12 UTC, madchicken commented on lib/src/graph.rs
> +    Normal(ConnectionPool),
What about `Direct`?

2025-01-09 16:14 UTC, madchicken commented on lib/src/messages.rs
> +        debug!("run query: {} with extra params {:?}", query, extra);
sorry, this is a leftover from my internal testing. It helped me to find a bug (I was passing context in the HELLO message when I should not). I can remove it.

2025-01-09 16:23 UTC, madchicken commented on lib/src/routing/connection_registry.rs
> +            debug!("Routing table is not expired");
Blocking the connection is going to slow down all the connections that are coming during the fetch and update process. I used a try_lock to reduce this slow down even tho I understand it's a minimal improvement. The solution that uses a separated thread should actually solve this issue.
I can change this with a lock and see how much it impacts on performances in a real environment.

2025-01-09 17:33 UTC, knutwalker commented
You said you are already planning a follow up for the update in the background, so we can also leave it as is until then.

On Thu, Jan 9, 2025, at 5:23 PM, Pierpaolo Follia wrote:
> 
> 
> ***@***.**** commented on this pull request.
> 
> 
> In lib/src/routing/connection_registry.rs <https://github.com/neo4j-labs/neo4rs/pull/205#discussion_r1909117374>:
> 
> > +                registry.retain(|k, _| servers.contains(k));
> +                let _ = self
> +                    .ttl
> +                    .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |_ttl| {
> +                        Some(routing_table.ttl)
> +                    })
> +                    .unwrap();
> +                debug!(
> +                    "Registry updated. New size is {} with TTL {}s",
> +                    registry.len(),
> +                    routing_table.ttl
> +                );
> +                *guard = now;
> +            }
> +        } else {
> +            debug!("Routing table is not expired");
> 
> 
> Blocking the connection is going to slow down all the connections that are coming during the fetch and update process. I used a try_lock to reduce this slow down even tho I understand it's a minimal improvement. The solution that uses a separated thread should actually solve this issue.
> I can change this with a lock and see how much it impacts on performances in a real environment.
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/neo4j-labs/neo4rs/pull/205#discussion_r1909117374>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAE2SX7QZR6BSNNQQCYGZHT2J2PAHAVCNFSM6AAAAABTV3KSECVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBQGM4DENRQGI>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2025-01-09 17:33 UTC, madchicken commented on lib/src/routing/connection_registry.rs
> +                };
I agree. Unfortunately I had to use this strategy to avoid a more substancial refactoring to the connection setup

2025-01-09 17:34 UTC, knutwalker commented
Direct sounds good, I like it!

On Thu, Jan 9, 2025, at 5:13 PM, Pierpaolo Follia wrote:
> 
> 
> ***@***.**** commented on this pull request.
> 
> 
> In lib/src/graph.rs <https://github.com/neo4j-labs/neo4rs/pull/205#discussion_r1909100530>:
> 
> >  };
> +use backoff::{Error, ExponentialBackoff};
> +use std::time::Duration;
> +
> +#[derive(Clone)]
> +enum ConnectionPoolManager {
> +    #[cfg(feature = "unstable-bolt-protocol-impl-v2")]
> +    Routed(RoutedConnectionManager),
> +    Normal(ConnectionPool),
> 
> What about `Direct`?
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/neo4j-labs/neo4rs/pull/205#discussion_r1909100530>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAE2SX7GJPZ5IG2QAJSLUSD2J2NY5AVCNFSM6AAAAABTV3KSECVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBQGM2TKNJQHA>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2025-01-10 08:42 UTC, knutwalker approved these changes
This is great, thanks!

2025-01-10 11:34 UTC, knutwalker commented
The 4.4 test failures are persistent enough that they might actually be related to this change 🤔

2025-01-10 17:30 UTC, knutwalker commented on lib/src/version.rs
>          bytes.put_u32(0);
you need to remove the two `put_u32(0)` calls. The initial message only expected 4 versions. I guess on 5.x, the server drains every additional bytes until the next message, on 4.4 those 0 values are part of the next message, effectively sending a few empty chunks.

2025-01-10 17:45 UTC, merged